# Generated by Django 5.1.1 on 2024-09-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='category',
            field=models.CharField(default='na', max_length=255),
            preserve_default=False,
        ),
    ]
