# Generated by Django 5.1.1 on 2024-10-04 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_uploadedfile_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='answers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
